### ISSUE TITLE
Blocking on knowing what people are working on.

### ISSUE THREAD

**Issue by jonleung** [hackclub/discussions#5]
I don't feel well enough informed about what other peolle are working on and visa versa. If someone asked me what Zach or Max is doing, I don't think I could really say anything more than One of our housemates right now and it seems that we are too small for this to happen already.

The async standups were meant to not take people away from flow but the I think granularity of what we have been doing is not enough. I am curious about what we may be losing out on becuase of this.

What do you guys think about doing more detailed standup notes? I'm going to try this tmr.

**Comment by MaxWofford** [comment]
Down to try this out tomorrow.

**Comment by jonleung** [comment]
Actually, was just thinking bout this again, I realize that if we do a good job at communicating what we are working on in our project management tool, we technically don't even need to do stand ups lol / we just paste our asana data here. I'd be happy to sit down with each person to brainstorm how to use Asana.

**Comment by MaxWofford** [comment]
@jonleung Why was this reopened?

**Comment by jonleung** [comment]
@MaxWofford because I accidentally closed it by accident.

**Comment by jonleung** [comment]
@zachlatta @MaxWofford  Also, I think task transparency within the organization is extremely important. It will allow everyone in the organization (and also outside the organization) to know what someone is doing at every given moment. So in whatever system we use, there's going to be that annoying bit of overhead. Asana seems to scale pretty well (see how the co-founder of Asana uses it https://asana.com/guide/more/examples/at-asana) At any given point, someone should be able to ask, I wonder what Jonathan is working on right now and be able to find out. Externally this could be important as well, but it seems like the resolution of that data and the level of privacy, especially for other people that we are dealing with. I want to optimize for people that are in our organization first over external people. Also because there is an API, we can write a script that selectively export, even possibly in real time what is going on. The API lets us filter which things we include in the public reporting to filter out sensitive data.

**Comment by zachlatta** [comment]
> I want to optimize for people that are in our organization first over ext ernal people.

Don't we want to consider _everyone_ a part of the organization? Isn't
the goal to have club leaders, club members, and anyone interested
contributing? Having that goal is particularly exciting to me and I
don't believe that having the default for task management be private is
conductive to that goal.

> At any given point, someone should be able to ask, I wonder what Jonathan is working on right now and be able to find out.

Wouldn't GitHub issues or a text file do this as well?

> Also because there is an API, we can write a script that selectively export, even possibly in real time what is going on. The API lets us filter which things we include in the public reporting to filter out sensitive data.

Are there any other organizations successfully doing this with Asana?
I'm worried that this leaves the default for the organization to
private, which is a half-baked solution to open-sourcing our internal
operations.

--
Zach Latta
Executive Director of hackEDU[https://hackedu.us/]
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta


On Wed, Apr 8, 2015, at 09:04 AM, jonleung wrote:
> @zachlatta[https://github.com/zachlatta] @MaxWofford[https://github.com/MaxWofford]  Also, I think task transparency within the organization is extremely important. It will allow everyone in the organization (and also outside the organization) to know what someone is doing at every given moment. So in whatever system we use, there's going to be that annoying bit of overhead. Asana seems to scale pretty well (see how the co-founder of Asana uses it https://asana.com/guide/more/examples/at-asana) At any given point, someone should be able to ask, I wonder what Jonathan is working on right now and be able to find out. Externally this could be important as well, but it seems like the resolution of that data and the level of privacy, especially for other people that we are dealing with. I want to optimize for people that are in our organization first 
 over ext
 ernal people. Also because there is an API, we can write a script that
 selectively export, even possibly in real time what is going on. The
 API lets us filter which things we include in the public reporting to
 filter out sensitive data.

**Comment by zachlatta** [comment]
Closing due to repo deprecation.
